server:
  port: 8003
  servlet:
    encoding:
      charset: utf-8

spring:
  application:
    name: log-collector
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
